spring:
  application:
    name: ejercicios-practica
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://dpg-dapeh8bm8hqs739h7b00-a.oregon-postgres.render.com:5432/biblioteca_db_fwx0?sslmode=require}
    username: ${POSTGRES_USER:biblioteca_db_fwx0_user}
    password: ${POSTGRES_PASSWORD:Ism1ZIB6ErhP1C2LXLqjm1EmU5x1cXAw}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET:mi-clave-super-secreta-de-desarrollo-local}
  expiration: 86400000  # 24hs en milisegundos

server:
  port: {$PORT:8080}